/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author FELIP
 */
public class VistaPaisUSUARIO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPaisUSUARIO.class.getName());
    
    /**
     * Creates new form VistaPaisUSUARIO
     */
        public VistaPaisUSUARIO() {
        initComponents();
        actualizarTabla();
        cargarFiltroPais();
        this.setLocationRelativeTo(null);
    }
        
    private void actualizarTabla(ArrayList<Modelo.Pais> listaPaisesAMostrar) {
    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    modeloTabla.addColumn("Nombre");
    modeloTabla.addColumn("Continente");
    modeloTabla.addColumn("Población");
    modeloTabla.addColumn("Código");
    
    for (Modelo.Pais p : listaPaisesAMostrar) {
        modeloTabla.addRow(new Object[]{
                p.getNombre(),
                p.getContinente(),
                p.getPoblacion(),
                p.getCodigo(),
            });
    }
        tblPais.setModel(modeloTabla);
}
    
    private void actualizarTabla() {
    actualizarTabla(com.mycompany.prueba2menu.main.listaPaises);
    DefaultTableModel modeloTabla = new DefaultTableModel();
    modeloTabla.addColumn("Nombre");
    modeloTabla.addColumn("Continente");
    modeloTabla.addColumn("Población");
    modeloTabla.addColumn("Codigo");
    
    for (Modelo.Pais p : com.mycompany.prueba2menu.main.listaPaises) {
        modeloTabla.addRow(new Object[]{
                p.getNombre(),
                p.getContinente(),
                p.getPoblacion(),
                p.getCodigo(),
                });
    }
tblPais.setModel(modeloTabla); 
}
    
    private void cargarFiltroPais() {
    DefaultComboBoxModel modelo = new DefaultComboBoxModel(); 
    modelo.addElement("Mostrar todo");
    Set<String> continentesUnicos = new HashSet<>();
    for (Modelo.Pais p : com.mycompany.prueba2menu.main.listaPaises) {
        continentesUnicos.add(p.getContinente().trim()); 
    }
    for (String continente : continentesUnicos) {
        modelo.addElement(continente);
    }
        cmbPais.setModel(modelo);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPais = new javax.swing.JTable();
        cmbPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tblPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Continente", "Poblacion", "Codigo"
            }
        ));
        jScrollPane1.setViewportView(tblPais);

        cmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPais, 0, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    VistaMenúUSUARIO vistaMenuU = new VistaMenúUSUARIO();
    this.setVisible(false);
    vistaMenuU.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cmbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisActionPerformed
        Object itemSeleccionado = cmbPais.getSelectedItem();
     
        if (itemSeleccionado == null || itemSeleccionado.toString().contains("Mostrar todo")) {
        actualizarTabla(com.mycompany.prueba2menu.main.listaPaises);
        return;
        }
        
        String filtro = itemSeleccionado.toString().trim().toLowerCase();
        ArrayList<Modelo.Pais> resultadosFiltrados = new ArrayList<>();
        for (Modelo.Pais p : com.mycompany.prueba2menu.main.listaPaises) {
        if (p.getContinente().trim().toLowerCase().equals(filtro)) {
                resultadosFiltrados.add(p);
        }
    }
        actualizarTabla(resultadosFiltrados);
        
    }//GEN-LAST:event_cmbPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPaisUSUARIO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPais;
    // End of variables declaration//GEN-END:variables
}
