/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import DAO.IdiomaDAO; 
import DAO.PaisDAO;   
import Modelo.IdiomaPais;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import Modelo.Pais; 
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FELIP
 */
public class VistaIdiomaUSUARIO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaIdiomaUSUARIO.class.getName());
    private final IdiomaDAO idiomaDAO = new IdiomaDAO();
    private final PaisDAO paisDAO = new PaisDAO();
    
    /**
     * Creates new form VistaIdiomaUSUARIO
     */
    public VistaIdiomaUSUARIO() {
        initComponents();
        cargarPaises(); 
        actualizarTabla();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIdioma = new javax.swing.JTable();
        cmbIdioma = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tblIdioma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Idioma", "Oficial", "Código país"
            }
        ));
        jScrollPane1.setViewportView(tblIdioma);

        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdiomaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("Idiomas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(182, 182, 182))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTabla(ArrayList<Modelo.IdiomaPais> listaIdiomasAMostrar) {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Idioma");
        modeloTabla.addColumn("Oficial");
        modeloTabla.addColumn("Código país");
        
        for (Modelo.IdiomaPais i : listaIdiomasAMostrar) {
                modeloTabla.addRow(new Object[]{
                i.getIdioma(),
                i.isEsOficial() ? "Si" : "No", 
                i.getPais().getNombre()
    });
        }
        tblIdioma.setModel(modeloTabla);
    }
    
    private void actualizarTabla() {
        ArrayList<IdiomaPais> listaIdiomas = idiomaDAO.listarIdiomas(); 
        actualizarTabla(listaIdiomas);   
        }
    
    private void cargarPaises() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel<>();    
        modelo.addElement("Mostrar todo");    
    
        ArrayList<Pais> listaPaises = paisDAO.listarPaises();
        
        for (Pais p : listaPaises) {                
                modelo.addElement(p.getNombre());
                }
        cmbIdioma.setModel(modelo);
    }
            
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    VistaMenúUSUARIO vistaMenuU = new VistaMenúUSUARIO();
    this.setVisible(false);
    vistaMenuU.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cmbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdiomaActionPerformed
        Object itemSeleccionado = cmbIdioma.getSelectedItem();
    
        if (itemSeleccionado == null || itemSeleccionado.toString().equals("Mostrar todo")) {
                actualizarTabla(); 
                return;
                }
        if (itemSeleccionado instanceof Pais) {
                Pais paisSeleccionado = (Pais) itemSeleccionado;
                String codigoPais = paisSeleccionado.getCodigo();           
                ArrayList<IdiomaPais> resultadosFiltrados = idiomaDAO.listarIdiomasPorPais(codigoPais); 
                actualizarTabla(resultadosFiltrados);
        }
    }//GEN-LAST:event_cmbIdiomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaIdiomaUSUARIO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIdioma;
    // End of variables declaration//GEN-END:variables
}
